### ISSUE TITLE
Email cleanup tracking

### ISSUE THREAD

**Issue by Trott** [nodejs/email#182]
- [ ] Audit admin/accounts/build email addresses
- [ ] The ci email address goes solely to @joaocgreis. It would be good to find out what it's for, whether it gets any email, and who else might be added to it.
- [ ] Audit ci-alert email address
- [x] The build-security address has @mmarchini and two other people who are (AFAIK) not active (@maclover7 and @gibfahn). It would be good to find out what it's for, whether it gets any email, and who else might be added to it.
- [ ] The security-ecosystem address goes to HackerOne. I don't believe it is taking any more reports. We should probably remove that email address? Or set up an auto-reply? Or maybe HackerOne sends a decent auto-reply?
- [x] The user-feedback email address is likely unused?
- [ ] Are we still doing CrowdIn and the nodejs-crowdin email address? If so, are @zeke and @obensource still the right people for that email address? Are there others?
- [ ] Audit i18n similar to nodejs-crowdin .
- [ ] Audit github-bot. It's mostly inactive people. Is the email address used?
- [ ] The node-slack-bot address goes to one (inactive?) person (@gdams). Does it get any email? Would it make sense to add some other folks?
- [ ] The website-redesign email doesn't seem to have the current and active website-redesign people? Is that email even necessary? Seems like the GitHub team is sufficient.
- [ ] Audit zoom-nodejs. (Seems like a somewhat weird mix of people. Who is on there and why? What is the purpose of the email address?)

_Originally posted by @Trott in https://github.com/nodejs/email/issues/181#issuecomment-1048829855_

**Comment by mhdawson** [comment]
I believe we can also remove crypto-report

**Comment by mhdawson** [comment]
Audit zoom-nodejs. (Seems like a somewhat weird mix of people. Who is on there and why? What is the purpose of the email address?)

Anybody who hosts zoom calls using the Node.js account should be on this list.  Needed to get authentication tokens that are sometimes needed.

**Comment by UlisesGascon** [comment]
> The security-ecosystem address goes to HackerOne. I don't believe it is taking any more reports. We should probably remove that email address? Or set up an auto-reply? Or maybe HackerOne sends a decent auto-reply?

Are we clear on this, @RafaelGSS ? Should we include it to the next meeting?

**Comment by RafaelGSS** [comment]
Yes, we should probably remove that email address.

**Comment by mmarchini** [comment]
>  The build-security address has @mmarchini and two other people who are (AFAIK) not active (@maclover7 and @gibfahn). It would be good to find out what it's for, whether it gets any email, and who else might be added to it.

No idea what that was for, didn't know it existed. Also seems like it was removed so you can check that as done: https://github.com/nodejs/email/commit/e8e43b2785e6cc8bd63689547deb6f92d3dc1135
